//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.CorrelationWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CorrelationWebService.CorrelationWebServiceSoap")]
    public interface CorrelationWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCorrelationId", ReplyAction="*")]
        System.Guid GetCorrelationId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCorrelationId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> GetCorrelationIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThrowError", ReplyAction="*")]
        void ThrowError();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThrowError", ReplyAction="*")]
        System.Threading.Tasks.Task ThrowErrorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CorrelationWebServiceSoapChannel : WebClient.CorrelationWebService.CorrelationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorrelationWebServiceSoapClient : System.ServiceModel.ClientBase<WebClient.CorrelationWebService.CorrelationWebServiceSoap>, WebClient.CorrelationWebService.CorrelationWebServiceSoap {
        
        public CorrelationWebServiceSoapClient() {
        }
        
        public CorrelationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorrelationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorrelationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorrelationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid GetCorrelationId() {
            return base.Channel.GetCorrelationId();
        }
        
        public System.Threading.Tasks.Task<System.Guid> GetCorrelationIdAsync() {
            return base.Channel.GetCorrelationIdAsync();
        }
        
        public void ThrowError() {
            base.Channel.ThrowError();
        }
        
        public System.Threading.Tasks.Task ThrowErrorAsync() {
            return base.Channel.ThrowErrorAsync();
        }
    }
}
